server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://192.168.1.247:3306/image_service?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/,file:${web.upload.path}

web.upload.path : C:/upload/images
ipAndPort : http://192.168.1.172:8888

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.hz.model
  #showSql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

localPath : "/upload/images/"

